// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIgbh1ZYm0_bo3w_IeqtzohnHoS4-gEU',
    appId: '1:333396883428:web:ea80dc85c9272fcc',
    messagingSenderId: '333396883428',
    projectId: 'pagosproumm',
    authDomain: 'pagosproumm.firebaseapp.com',
    databaseURL: 'https://pagosproumm.firebaseio.com',
    storageBucket: 'pagosproumm.appspot.com',
    measurementId: 'G-W8NVFPKE2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4_Seg-0HTngSSPAnNuE6euyVJ_bFsuS0',
    appId: '1:333396883428:android:43b73503ee95fdf49c79f1',
    messagingSenderId: '333396883428',
    projectId: 'pagosproumm',
    databaseURL: 'https://pagosproumm.firebaseio.com',
    storageBucket: 'pagosproumm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlG5vKyYCL9cDhZTtITFvnSzr-0rf6vI',
    appId: '1:333396883428:ios:e9e858e3f8c44bc29c79f1',
    messagingSenderId: '333396883428',
    projectId: 'pagosproumm',
    databaseURL: 'https://pagosproumm.firebaseio.com',
    storageBucket: 'pagosproumm.appspot.com',
    androidClientId: '333396883428-at9p7sdcc6i13ktmovbp8n5771togqu8.apps.googleusercontent.com',
    iosBundleId: 'com.monosoft.thinkBack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtlG5vKyYCL9cDhZTtITFvnSzr-0rf6vI',
    appId: '1:333396883428:ios:5572a8e70ff07d589c79f1',
    messagingSenderId: '333396883428',
    projectId: 'pagosproumm',
    databaseURL: 'https://pagosproumm.firebaseio.com',
    storageBucket: 'pagosproumm.appspot.com',
    androidClientId: '333396883428-at9p7sdcc6i13ktmovbp8n5771togqu8.apps.googleusercontent.com',
    iosBundleId: 'com.monosoft.thinkBack.RunnerTests',
  );
}
